[platformio]
default_envs = m5paper

[env:m5paper]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_ldf_mode = deep+
lib_deps =
  m5stack/M5Unified@^0.2.23
  bblanchon/ArduinoJson@^6.21.5
  knolleary/PubSubClient@^2.8
  greiman/SdFat@^2.3.1
  https://github.com/Seeed-Studio/PN532.git
  https://github.com/marian-craciunescu/ESP32Ping.git
build_flags =
  -DPAPEROS_TARGET_M5PAPER_V1=1
  -DPAPEROS_VERSION=\"0.2.0-alpha\"
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue

[env:m5paper-debug]
extends = env:m5paper
build_type = debug
build_flags =
  ${env:m5paper.build_flags}
  -DCORE_DEBUG_LEVEL=4
